### ISSUE TITLE
Locations count in an API request

### ISSUE THREAD

**Issue by julianshutt** [milesgranger/elevation-api-public#35]
Hello!

I am integrating the elevations API into a routing application and am having some problems with the number of waypoints I can include in an API request.

For example, the following call contains *six* locations, under the ten that I believe the request supports,
> [https://elevation-api.io/api/elevation?points=(51.9385704,-2.4214404)(51.93377470000001,-2.407834)(51.87476770000001,-2.2669835)(51.8760084,-2.2408741)(51.8882505,-2.1862001)(51.89352890000001,-2.1498523)&key=foo](https://elevation-api.io/api/elevation?points=(51.9385704,-2.4214404)(51.93377470000001,-2.407834)(51.87476770000001,-2.2669835)(51.8760084,-2.2408741)(51.8882505,-2.1862001)(51.89352890000001,-2.1498523)&key=foo)

...though I am being informed that the request contains more than ten locations in the API response,

```
{
  "message": "Requested more than 10 locations, please reduce the request size."
}
```

If I reduce it by one location to *five* locations, then I get a valid response - could it be that the # of lat/long values and not the number of lat/long locations are being counted? Very possible I am reading the constraint incorrectly!

Thanks in advance!

**Comment by milesgranger** [comment]
Hi! Wow, that is indeed a bug. I'll try and have the fix out by tomorrow! 
Thanks for letting me know! :+1:

**Comment by milesgranger** [comment]
Hi again! This is now fixed, thanks again for reporting it! :100:
