### ISSUE TITLE
Elevation not returned on new account with $1 balance

### ISSUE THREAD

**Issue by systemed** [milesgranger/elevation-api-public#38]
If I request

    https://elevation-api.io/api/elevation?points=(46.2219,13.5022),(46.2181,13.4987)&key=<my API key>&resolution=5

then the result is elevation at 5000m resolution. The account is new and has $1 balance on it.

If there's a minimum balance required for queries, it would be good to document this. If a key-authenticated API call fails, it would be good if the JSON response included the reason for failure, rather than just opaquely returning a 5000m response.

**Comment by milesgranger** [comment]
Hi there!

This is because 5 isn't a valid resolution. Supported ones are 30 and 90, as well as postfixing those with "-interpolated", such as "90-interpolated"

Let me know if you have other issues, but perhaps I could update the docs to be more explicit about this.

Thanks! 👍

**Comment by milesgranger** [comment]
Also, I agree that if "resolution" is supplied, it should indeed result in a bad request with the reason. 👍

**Comment by systemed** [comment]
Thank you!
