### ISSUE TITLE
Geotiff and Coordinate system

### ISSUE THREAD

**Issue by maka1000** [milesgranger/elevation-api-public#41]
Hi

Is it possible to import several geotiff files? Which coordinate systems are supported?

**Comment by milesgranger** [comment]
Hi!

I'm not sure what you mean by importing several geotiff files, could you elaborate?

For the coordinate system, the API is based on WGS84 based files.

**Comment by maka1000** [comment]
Hi

Yes sure:
For the most area of the world we would use the usual srtm (hgt) files. But for some areas we have more accurate files in another file format (geotiff) and in another coordinate system then wgs84.

So for example:
For a request in the area of France the system use the data of the usual srtm files. But for a request in the area of Germany the system use another dataset in format geotiff and in another coordinate system.

**Comment by milesgranger** [comment]
Forgive me, but are you sure you're opening this issue in the correct project? This is the 'public' interface to https://elevationa-api.io, it sounds like you may be meaning to question about importing your own data for another open-source alternative? The data using in my API are all SRTM format files, no GeoTiffs. Maybe you meant to open this in https://github.com/Jorl17/open-elevation?

**Comment by maka1000** [comment]
Hi
Oh so it is not possible to use your project to setup an own api on my server?

**Comment by milesgranger** [comment]
Correct, sorry about the confusion. It was open-source and you may have been able to do as you say, but the hosted version was paid by donations and got a massive amount of traffic but no one ever donated, so took it to a 'freemium' model.
